//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfpr3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int id { get; set; }
        public string citizenship { get; set; }
        public int statusID { get; set; }
        public string livingcity { get; set; }
        public int educationID { get; set; }
        public Nullable<int> langID { get; set; }
        public Nullable<int> levelID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Education Education { get; set; }
        public virtual Language Language { get; set; }
        public virtual Level Level { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
