//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfpr3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CadrAgencyEntities : DbContext
    {
        private static CadrAgencyEntities _context;
        public CadrAgencyEntities()
            : base("name=CadrAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static CadrAgencyEntities GetContext()
        {
            if(_context == null)
            {
                _context = new CadrAgencyEntities();
            }
            return _context;
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Appstatus> Appstatuses { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Network> Networks { get; set; }
        public virtual DbSet<Resume> Resumes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vacancy> Vacancies { get; set; }
        public virtual DbSet<Vacanciestatu> Vacanciestatus { get; set; }
    }
}
