//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfpr3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class User
    {
        public int id { get; set; }
        [Required]
        public int roleID { get; set; }
        [Required(ErrorMessage = "Firstname is required.")]
        public string firstname { get; set; }
        [Required(ErrorMessage = "Surname is required.")]
        public string surname { get; set; }
        [Required(ErrorMessage = "Birthday is required.")]
        public System.DateTime birthday { get; set; }
        [Required(ErrorMessage = "Phone is required.")]
        public string phone { get; set; }
        [Required(ErrorMessage = "Email is required.")]
        public string email { get; set; }
        [Required(ErrorMessage = "Password is required.")]
        public string hashpass { get; set; }
        public Nullable<int> networkID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual Network Network { get; set; }
        public virtual Role Role { get; set; }
    }
}
