//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfpr3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public int roleID { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public System.DateTime birthday { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string hashpass { get; set; }
        public Nullable<int> networkID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual Network Network { get; set; }
        public virtual Role Role { get; set; }
    }
}
